create database Retail_Data_Analysis

	   SELECT* FROM Customer
	   SELECT* FROM Transactions
	   SELECT* FROM prod_cat_info



--What is the total number of rows in each of the 3 tables in the database? 
SELECT (SELECT COUNT(*) FROM Customer) AS CustCnt,
       (SELECT COUNT(*) FROM Transactions) AS TransCnt,     
       (SELECT COUNT(*) FROM prod_cat_info) AS ProdCnt



--What is the total number of transactions that have a return? 
SELECT COUNT(TOTAL_AMT) as total_amt
FROM Transactions
WHERE TOTAL_AMT LIKE '-%'




--As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.
SELECT CONVERT(DATE, DOB, 105) AS DATES 
FROM Customer

SELECT CONVERT(DATE, tran_date, 105) AS tran_date
FROM Transactions


--What is the time range of the transaction data available for analysis? Show the output in number of days, months and year simultaneously in different columns.
SELECT DATEDIFF(DAY, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105)))as Day, 
DATEDIFF(MONTH, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))) as month,  
DATEDIFF(YEAR, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))) as year 
FROM Transactions



--Which product category does the sub-category "DIY" belong to?
SELECT prod_cat
FROM prod_cat_info
WHERE prod_subcat LIKE 'DIY'



--DATA ANALYSIS

--Which channel is most frequently used for transactions?
SELECT TOP 1 Store_type, COUNT(transaction_id) Count_
FROM Transactions 
GROUP BY Store_type
ORDER BY COUNT(transaction_id) DESC

--What is the count of Male and Female customers in the database?
SELECT Gender, COUNT(customer_Id) AS COUNTG
FROM Customer
WHERE Gender IN ('M' , 'F')
GROUP BY Gender

--From which city do we have the maximum number of customers and how many?
SELECT top 1
city_code, COUNT(customer_Id) CUST_CNT
FROM Customer
GROUP BY city_code
ORDER BY CUST_CNT DESC

--How many sub-categories are there under the Books category?
SELECT COUNT(prod_subcat) AS SUBCAT_CNT
FROM prod_cat_info
WHERE prod_cat = 'Books'
GROUP BY prod_cat

--What is the maximum quantity of products ever ordered?
SELECT TOP 1 Qty 
FROM Transactions
ORDER BY Qty DESC

--What is the net total revenue generated in categories Electronics and Books?
SELECT SUM(total_amt) AMOUNT
FROM Transactions as t
JOIN prod_cat_info as p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE prod_cat IN ('BOOKS' , 'ELECTRONICS')

--How many customers have >10 transactions with us, excluding returns?
SELECT COUNT(customer_Id) AS CUSTOMER_COUNT
FROM Customer 
WHERE customer_Id IN 
(
SELECT cust_id
FROM Transactions as t
JOIN Customer as c
ON t.cust_id = c.customer_Id
WHERE total_amt NOT LIKE '-%'
GROUP BY cust_id
HAVING COUNT(transaction_id) > 10
)


--What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
SELECT SUM(total_amt) AS AMOUNT 
FROM Transactions as t
JOIN prod_cat_info as p
ON p.prod_cat_code = t.prod_cat_code 
AND p.prod_sub_cat_code = t.prod_subcat_code
WHERE prod_cat IN ('CLOTHING','ELECTRONICS') AND STORE_TYPE = 'FLAGSHIP STORE'


--What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by	prod sub-cat.
SELECT prod_subcat, SUM(total_amt) REVENUE
FROM Transactions as t
JOIN Customer as c
ON c.customer_Id=t.cust_id
JOIN prod_cat_info as p
ON p.prod_cat_code = t.prod_cat_code and p.prod_sub_cat_code = t.prod_subcat_code
WHERE p.prod_cat_code = '3' AND Gender = 'M'
GROUP BY prod_subcat_code, prod_subcat


--What is percentage of sales and returns by product sub category display only top 5 sub categories in terms of sales?
SELECT TOP 5 prod_subcat, (SUM(total_amt)*100/(SELECT SUM(total_amt) FROM Transactions)) AS PERCANTAGE_OF_SALES, 
(COUNT(CASE WHEN Qty< 0 THEN Qty ELSE NULL END)*100 /SUM(Qty)) AS PERCENTAGE_OF_RETURN
FROM Transactions as t
JOIN prod_cat_info as p
ON p.prod_cat_code = t.prod_cat_code AND t.prod_subcat_code= p.prod_sub_cat_code
GROUP BY prod_subcat
ORDER BY SUM(total_amt) DESC


--For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?
SELECT cust_id,SUM(total_amt) AS REVENUE 
FROM Transactions
WHERE cust_id IN 
	(SELECT customer_Id
	 FROM Customer
     WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
     AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)) 
	 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
GROUP BY cust_id



--Which product category has seen the max value of returns in the last 3 months of transactions?
SELECT TOP 1 prod_cat, SUM(total_amt) as total
FROM Transactions as t
JOIN prod_cat_info as p 
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE total_amt < 0 AND CONVERT(date, tran_date, 103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)) 
	 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
GROUP BY prod_cat
ORDER BY 2 DESC

--Which store-type sells the maximum products; by value of sales amount and	by quantity sold?
SELECT  Store_type, SUM(total_amt) Total_SALES, SUM(Qty) Total_Qty
FROM Transactions
GROUP BY Store_type
HAVING SUM(total_amt) >=ALL (SELECT SUM(total_amt) FROM Transactions GROUP BY Store_type)
AND SUM(Qty) >=ALL (SELECT SUM(Qty) FROM Transactions GROUP BY Store_type)

--What are the categories for which average revenue is above the overall average.
SELECT prod_cat, AVG(total_amt) AS AVERAGE
FROM Transactions as t
JOIN prod_cat_info as p
ON p.prod_cat_code=t.prod_cat_code AND t.prod_subcat_code=p.prod_sub_cat_code
GROUP BY prod_cat
HAVING AVG(total_amt)> (SELECT AVG(total_amt) FROM Transactions) 


--Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
SELECT top 5 prod_subcat, AVG(total_amt) AS AVERAGE_REV, SUM(total_amt) AS REVENUE
FROM Transactions as t
JOIN prod_cat_info as p
ON p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
WHERE prod_cat IN
(
SELECT TOP 5 
prod_cat
FROM Transactions as t 
JOIN prod_cat_info as p
ON p.prod_cat_code= t.prod_cat_code AND p.prod_sub_cat_code = t.prod_subcat_code
GROUP BY prod_cat
ORDER BY SUM(Qty) DESC
)
GROUP BY  prod_subcat;

